#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued term

fibonacci = [1, 2]
x = 0
i = 0

while x < 4*(10**6):
    x = fibonacci[i] + fibonacci[i + 1]
    fibonacci.append(x)
    i += 1
  
print(sum([f for f in fibonacci if f % 2 == 0]))
